apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: frontend-mongo-pacman-hpxm
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: frontend-mongo-pacman-hpxm
    app.kubernetes.io/part-of: mongo-pacman
  name: frontend-mongo-pacman-hpxm
spec:
  ports:
  - port: 8080
    targetPort: 8080
  selector:
    app.kubernetes.io/instance: frontend-mongo-pacman-hpxm
status:
  loadBalancer: {}
