apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: mongo-mongo-pacman-wtom
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: mongo-mongo-pacman-wtom
    app.kubernetes.io/part-of: mongo-pacman
  name: mongo-mongo-pacman-wtom
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app.kubernetes.io/instance: mongo-mongo-pacman-wtom
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/instance: mongo-mongo-pacman-wtom
    spec:
      containers:
      - image: quay.io/northdepot/user1-tenant/mongo-pacman/mongo-mongo-pacman-wtom@sha256:b04c68bdfba9dee94e7d84309bf87e88301a74839d891dfa203d987a280597da
        imagePullPolicy: Always
        name: container-image
        ports:
        - containerPort: 27017
        resources:
          limits:
            cpu: 100m
            memory: 512Mi
          requests:
            cpu: 10m
            memory: 512Mi
status: {}
